export const dummySaleItems = [
  {
    id: 's1',
    type: 'Kohaku',
    farm: 'Dainichi Koi Farm',
    price: 'Rp 500.000',
    location: 'Magelang',
    grade: 'A',
    size: '35 cm',
    imageUrl: 'https://unsplash.com/photos/fwSNS_0Awq4/download?w=600',
  },
  {
    id: 's2',
    type: 'Showa',
    farm: 'Marudo Koi Farm',
    price: 'Rp 750.000',
    location: 'Blitar',
    grade: 'A',
    size: '40 cm',
    imageUrl: 'https://unsplash.com/photos/h_4fe8fmb1E/download?w=600',
  },
  {
    id: 's3',
    type: 'Sanke',
    farm: 'Hikari Koi Farm',
    price: 'Rp 600.000',
    location: 'Magelang',
    grade: 'B',
    size: '30 cm',
    imageUrl: 'https://unsplash.com/photos/S5RwcwBS2lQ/download?w=600',
  },
  {
    id: 's4',
    type: 'Yamabuki',
    farm: 'Amanuma Farm',
    price: 'Rp 450.000',
    location: 'Malang',
    grade: 'A',
    size: '32 cm',
    imageUrl: 'https://unsplash.com/photos/7rR_WSk4HM0/download?w=600',
  },
  {
    id: 's5',
    type: 'Tancho',
    farm: 'Sakai Fish Farm',
    price: 'Rp 1.250.000',
    location: 'Surabaya',
    grade: 'A+',
    size: '45 cm',
    imageUrl: 'https://unsplash.com/photos/pw8vGbh4Bu0/download?w=600',
  },
  {
    id: 's6',
    type: 'Asagi',
    farm: 'Oya Koi Farm',
    price: 'Rp 350.000',
    location: 'Bandung',
    grade: 'B',
    size: '25 cm',
    imageUrl: 'https://unsplash.com/photos/SjcrpttvjiE/download?w=600',
  },
];

export const dummyAuctionItems = [
  {
    id: 'a1',
    type: 'Showa',
    farm: 'Dainichi Koi Farm',
    currentBid: 'Rp 1.200.000',
    location: 'Blitar',
    grade: 'A',
    size: '40 cm',
    bidders: 15,
    endTime: new Date(Date.now() + 3600000 * 2.5).getTime(),
    imageUrl: 'https://unsplash.com/photos/pw8vGbh4Bu0/download?w=600',
  },
  {
    id: 'a2',
    type: 'Kohaku',
    farm: 'Marusei Koi Farm',
    currentBid: 'Rp 850.000',
    location: 'Magelang',
    grade: 'A',
    size: '35 cm',
    bidders: 9,
    endTime: new Date(Date.now() + 3600000 * 1.25).getTime(),
    imageUrl: 'https://unsplash.com/photos/SjcrpttvjiE/download?w=600',
  },
  {
    id: 'a3',
    type: 'Shiro Utsuri',
    farm: 'Omosako Farm',
    currentBid: 'Rp 2.100.000',
    location: 'Surabaya',
    grade: 'A+',
    size: '50 cm',
    bidders: 24,
    endTime: new Date(Date.now() + 3600000 * 4.5).getTime(),
    imageUrl: 'https://unsplash.com/photos/fwSNS_0Awq4/download?w=600',
  },
  {
    id: 'a4',
    type: 'Sanke',
    farm: 'Matsunosuke',
    currentBid: 'Rp 1.550.000',
    location: 'Malang',
    grade: 'A',
    size: '42 cm',
    bidders: 12,
    endTime: new Date(Date.now() + 3600000 * 3.1).getTime(),
    imageUrl: 'https://unsplash.com/photos/h_4fe8fmb1E/download?w=600',
  },
  {
    id: 'a5',
    type: 'Kujaku',
    farm: 'Kaneko Koi Farm',
    currentBid: 'Rp 450.000',
    location: 'Tulungagung',
    grade: 'B+',
    size: '30 cm',
    bidders: 5,
    endTime: new Date(Date.now() + 3600000 * 0.5).getTime(),
    imageUrl: 'https://unsplash.com/photos/7rR_WSk4HM0/download?w=600',
  },
  {
    id: 'a6',
    type: 'Ochiba',
    farm: 'Chogoro',
    currentBid: 'Rp 950.000',
    location: 'Jakarta',
    grade: 'A',
    size: '38 cm',
    bidders: 18,
    endTime: new Date(Date.now() + 3600000 * 12).getTime(),
    imageUrl: 'https://unsplash.com/photos/S5RwcwBS2lQ/download?w=600',
  }
];

export const dummyPremiumSellers = [
  { id: 'ps1', name: 'Sakai Farm', location: 'Blitar', rating: 4.9, avatar: 'https://i.pravatar.cc/150?img=11' },
  { id: 'ps2', name: 'Dainichi', location: 'Kediri', rating: 4.8, avatar: 'https://i.pravatar.cc/150?img=33' },
  { id: 'ps3', name: 'Momotaro', location: 'Tulungagung', rating: 5.0, avatar: 'https://i.pravatar.cc/150?img=59' },
  { id: 'ps4', name: 'Marudo', location: 'Magelang', rating: 4.7, avatar: 'https://i.pravatar.cc/150?img=68' },
  { id: 'ps5', name: 'Isa Koi', location: 'Surabaya', rating: 4.9, avatar: 'https://i.pravatar.cc/150?img=12' },
  { id: 'ps6', name: 'Kondo', location: 'Malang', rating: 4.6, avatar: 'https://i.pravatar.cc/150?img=15' },
];

export const dummyVideos = [
  { id: 'v1', prize: 'JUARA 1 14.000.000', title: 'Grand Champion 2023', imageUrl: 'https://unsplash.com/photos/fwSNS_0Awq4/download?w=600' },
  { id: 'v2', prize: 'JUARA 2 8.000.000', title: 'Runner Up Blitar Show', imageUrl: 'https://unsplash.com/photos/SjcrpttvjiE/download?w=600' },
  { id: 'v3', prize: 'JUARA 3 5.000.000', title: 'Best in Size 40Bu', imageUrl: 'https://unsplash.com/photos/pw8vGbh4Bu0/download?w=600' },
  { id: 'v4', prize: 'BEST TATEGOI', title: 'Pilihan Juri Kategori Tategoi', imageUrl: 'https://unsplash.com/photos/h_4fe8fmb1E/download?w=600' },
  { id: 'v5', prize: 'JUARA HARAPAN', title: 'Kategori Kohaku 35cm', imageUrl: 'https://unsplash.com/photos/S5RwcwBS2lQ/download?w=600' },
  { id: 'v6', prize: 'BEST LOCAL', title: 'Kejuaraan Koi Lokal Terbaik', imageUrl: 'https://unsplash.com/photos/7rR_WSk4HM0/download?w=600' },
];
